# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count the number of lines in a file
#'
#' @useDynLib CollapsABEL
#' @importFrom Rcpp sourceCpp evalCpp
#' @param fn Input filepath
#' @return A integer for the number of lines
#' @export
#' @examples
#' countlines("/tmp/x.txt")
countlines <- function(fn) {
    .Call('CollapsABEL_countlines', PACKAGE = 'CollapsABEL', fn)
}

#' Counts the number of columns of whitespace delimited file.
#'
#' @param fn Input filepath
#' @return A integer for the number of columns
#' @export
#' @examples
#' ncols("/tmp/x.txt")
ncols <- function(fn) {
    .Call('CollapsABEL_ncols', PACKAGE = 'CollapsABEL', fn)
}

#' print all the lines of a text file.
#'
#' @param fn Input filepath
#' @export
#' @examples
#' printlines("/tmp/x.txt")
printlines <- function(fn) {
    invisible(.Call('CollapsABEL_printlines', PACKAGE = 'CollapsABEL', fn))
}

#' Read one column of a whitespace delimited text file
#'
#' @param fileName Input filepath
#' @param colNum An integer. The target column number
#' @param nSkip An integer. Number of lines to skip in the beginning. 
#' @param maxRowNum An Integer. Maximum number of lines to read
#' @return A vector of strings containing the target column
#' @export
#' @examples
#' readcol("/tmp/x.txt", 2, 1, 15)
readcol <- function(fileName, colNum, nSkip, maxRowNum) {
    .Call('CollapsABEL_readcol', PACKAGE = 'CollapsABEL', fileName, colNum, nSkip, maxRowNum)
}

#' Read columns of a whitespace delimited text file
#'
#' @param fn input filepath
#' @param colsel a vector of target column numbers
#' @param nFirstSkipLines Integer. Number of lines to skip in the beginning
#' @param nSkipUnit Integer M. Let the function read one line out of every M
#' @return A matrix of strings from selected columns
#' @export
#' @examples
#' readcol("/tmp/x.txt", c(1, 3, 5), 1, 3)
readcols <- function(fn, colsel, nFirstSkipLines, nSkipUnit) {
    .Call('CollapsABEL_readcols', PACKAGE = 'CollapsABEL', fn, colsel, nFirstSkipLines, nSkipUnit)
}

