// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countlines
size_t countlines(std::string fn);
RcppExport SEXP CollapsABEL_countlines(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    __result = Rcpp::wrap(countlines(fn));
    return __result;
END_RCPP
}
// ncols
size_t ncols(std::string fn);
RcppExport SEXP CollapsABEL_ncols(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    __result = Rcpp::wrap(ncols(fn));
    return __result;
END_RCPP
}
// printlines
void printlines(std::string fn);
RcppExport SEXP CollapsABEL_printlines(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    printlines(fn);
    return R_NilValue;
END_RCPP
}
// readcol
std::vector< std::string > readcol(std::string fileName, size_t colNum, size_t nSkip, size_t maxRowNum);
RcppExport SEXP CollapsABEL_readcol(SEXP fileNameSEXP, SEXP colNumSEXP, SEXP nSkipSEXP, SEXP maxRowNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< size_t >::type colNum(colNumSEXP);
    Rcpp::traits::input_parameter< size_t >::type nSkip(nSkipSEXP);
    Rcpp::traits::input_parameter< size_t >::type maxRowNum(maxRowNumSEXP);
    __result = Rcpp::wrap(readcol(fileName, colNum, nSkip, maxRowNum));
    return __result;
END_RCPP
}
// readcols
Rcpp::CharacterMatrix readcols(std::string fn, std::vector<unsigned long> colsel, size_t nFirstSkipLines, size_t nSkipUnit);
RcppExport SEXP CollapsABEL_readcols(SEXP fnSEXP, SEXP colselSEXP, SEXP nFirstSkipLinesSEXP, SEXP nSkipUnitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< std::vector<unsigned long> >::type colsel(colselSEXP);
    Rcpp::traits::input_parameter< size_t >::type nFirstSkipLines(nFirstSkipLinesSEXP);
    Rcpp::traits::input_parameter< size_t >::type nSkipUnit(nSkipUnitSEXP);
    __result = Rcpp::wrap(readcols(fn, colsel, nFirstSkipLines, nSkipUnit));
    return __result;
END_RCPP
}
